% first test for new 1-at-a-time components analysis
[x, hname] = system('hostname');
hname = deblank(hname);
switch hname
    case 'peseta.cs.stir.ac.uk'
        f101dir = '/Volumes/Extra/AllenCorpus/AllenCorpus/f101' ;
        m102dir = '/Volumes/Extra/AllenCorpus/AllenCorpus/m102' ;
    case 'Leslie-Smiths-MacBook-Pro.local'
        f101dir = '../SoundStimuli_2019/f101' ;
        m102dir = '../SoundStimuli_2019/m102' ;
    otherwise
        disp('Computer name not known: add paths to case statement') ;
end
weight1 = spectrotemporal2(f101dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 4, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true) ;
weight2 = spectrotemporal2(f101dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight1) ;
weight2a = [weight1 ; weight2] ;
weight3 = spectrotemporal2(f101dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight2a) ;
weight3a = [weight2a; weight3] ;
weight4 = spectrotemporal2(f101dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight3a) ;
weight4a = [weight3a; weight3] ;
weight5 = spectrotemporal2(f101dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight4a) ;
save([f101dir '/' 'f101_weights.mat'], 'weight1', 'weight2', 'weight3', 'weight4', 'weight5') 

weight1 = spectrotemporal2(m102dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 4, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true) ;
weight2 = spectrotemporal2(m102dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight1) ;
weight2a = [weight1 ; weight2] ;
weight3 = spectrotemporal2(m102dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight2a) ;
weight3a = [weight2a; weight3] ;
weight4 = spectrotemporal2(m102dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight3a) ;
weight4a = [weight3a; weight3] ;
weight5 = spectrotemporal2(m102dir, 'filelist_10.txt', 'fs', 16000, 'useabs', true, ...
            'useonset', false, 'useoffset', false, 'weightnorm', 8, 'LIFrp', 0.025, ...
            'k_fired', 0.002, 'k_notfired', 0.001,'liftimestep', 0.0025, ...
            'lifdissipation', 20, 'debug', true, 'existingweights', weight4a) ;
save([m102dir '/' 'm102_weights.mat'], 'weight1', 'weight2', 'weight3', 'weight4', 'weight5') ;

